name: Sync R1 to R2

on:
  push:
    branches: [R1]

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: R1

      - name: Setup GH CLI
        run: |
          gh --version || sudo apt-get install gh -y
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create and merge PR
        id: sync
        run: |
          # Create PR and capture URL
          PR_URL=$(gh pr create \
            --head R1 \
            --base R2 \
            --title "Auto-sync: R1 → R2" \
            --body "Automated sync")
          echo "PR_URL=$PR_URL" >> $GITHUB_OUTPUT
          
          # Merge PR
          gh pr merge "$PR_URL" --merge --admin

      - name: Trigger deployment with PR URL
        run: |
          gh workflow run deploy.yaml \
            --ref R2 \
            -f pr_url="${{ steps.sync.outputs.PR_URL }}"
