name: Sync R1 to R2 with Webhook Simulation

on:
  push:
    branches: [R1]  # Trigger when changes land in R1

jobs:
  sync-and-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write  # Required for workflow dispatch
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: R1

      - name: Setup GH CLI
        run: |
          gh --version || sudo apt-get install gh -y
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create PR from R1 to R2
        id: create-pr
        run: |
          PR_URL=$(gh pr create \
            --head R1 \
            --base R2 \
            --title "Auto-sync: R1 → R2" \
            --body "Automated sync")
          echo "PR_URL=$PR_URL" >> $GITHUB_OUTPUT
          echo "PR_NUMBER=$(echo $PR_URL | grep -oE '[0-9]+$')" >> $GITHUB_OUTPUT

      - name: Merge PR (admin override)
        run: |
          gh pr merge "$PR_URL" --merge --admin 
        env:
          PR_URL: ${{ steps.create-pr.outputs.PR_URL }}

      - name: Simulate pull_request:closed webhook
        run: |
          # Get PR details
          PR_JSON=$(gh pr view ${{ steps.create-pr.outputs.PR_NUMBER }} --json headRefName,baseRefName,merged)
          
          # Send simulated webhook (requires admin PAT)
          curl -X POST \
            -H "Authorization: token ${{ secrets.ADMIN_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{
              "event_type": "simulated_pr_close",
              "client_payload": {
                "action": "closed",
                "merged": true,
                "pull_request": '$PR_JSON'
              }
            }'
        env:
          ADMIN_PAT: ${{ secrets.ADMIN_PAT }}  # PAT with repo/admin permissions
